application: interpretthis-budget
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

builtins:
- datastore_admin: on
